version: "3.8"

name: HB_API-Gateway_prod
services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    container_name: HB_API-Gateway_prod
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      NODE_ENV: production
    networks:
      - healthbridge-network

networks:
  healthbridge-network:
    driver: bridge
