# =====================================================
# subscription-service/docker-compose.yml
# Entorno de desarrollo (hot reload)
# =====================================================

version: "3.8"

name: HB_subscription-service_dev
services:
  mongodb:
    image: mongo:7.0
    container_name: HB_subscription-service_mongodb_dev
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongodb_data:/data/db
    networks:
      - healthbridge-network

  subscription-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.development
    container_name: HB_subscription-service_dev
    restart: always
    ports:
      - "3007:3007"
    environment:
      PORT: 3007
      NODE_ENV: development
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
    networks:
      - healthbridge-network

volumes:
  mongodb_data:

networks:
  healthbridge-network:
    driver: bridge
