# =====================================================
# auth-service/docker-compose.yml
# Entorno de desarrollo (hot reload)
# =====================================================

version: "3.8"

name: HB_auth-service_dev
services:
  mongodb:
    image: mongo:7.0
    container_name: HB_auth-service_mongodb_dev
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongodb_data:/data/db
    networks:
      - healthbridge-network

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.development
    container_name: HB_auth-service_dev
    restart: always
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      NODE_ENV: development
      MONGODB_URI: mongodb+srv://osquimenacho2002_db_user:LLLWy0c83sos1xN0@healthbridge.pykxi5g.mongodb.net/HB_auth-service_dev_DB?retryWrites=true&w=majority&appName=HealthBridge
      JWT_SECRET: healthbridge-jwt-secret-dev
      JWT_REFRESH_SECRET: healthbridge-refresh-secret-dev
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
    networks:
      - healthbridge-network


volumes:
  mongodb_data:

networks:
  healthbridge-network:
    driver: bridge
