# =====================================================
# auth-service/docker-compose.prod.yml
# Entorno de producción (imagen limpia y compilada)
# =====================================================

version: "3.8"

name: HB_auth-service_prod
services:
  mongodb:
    image: mongo:7.0
    container_name: HB_auth-service_mongodb_prod
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongodb_data:/data/db
    networks:
      - healthbridge-network

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    container_name: HB_auth-service_prod
    restart: always
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      NODE_ENV: production
      MONGODB_URI: mongodb+srv://osquimenacho2002_db_user:LLLWy0c83sos1xN0@healthbridge.pykxi5g.mongodb.net/HB_auth-service_prod_DB?retryWrites=true&w=majority&appName=HealthBridge
      JWT_SECRET: healthbridge-jwt-secret-prod
      JWT_REFRESH_SECRET: healthbridge-refresh-secret-prod
    depends_on:
      - mongodb
    networks:
      - healthbridge-network

volumes:
  mongodb_data:

networks:
  healthbridge-network:
    driver: bridge
